test install script:
  image: quiqqer/testing:2-php8.1
  script:
  - sudo chmod +x install-script.sh
  - ./install-script.sh "${CI_PROJECT_DIR}"
  - cd /var/www/html/packages/quiqqer/test
  - PHPSTAN_VERSION_CONSTRAINT=
  - if [ -z ${PHPSTAN_VERSION_CONSTRAINT} ]; then PHPSTAN_VERSION_CONSTRAINT=$(phive
    --no-progress --home ${CI_PROJECT_DIR}/.phive-home status | { grep phpstan ||
    test $? = 1; } | awk '{print $2}'); fi
  - phive --no-progress --home ${CI_PROJECT_DIR}/.phive-home install --temporary --trust-gpg-keys
    51C67305FFC2E5C0,CA7C2C7A30C8E8E1274A847651C67305FFC2E5C0 phpstan@${PHPSTAN_VERSION_CONSTRAINT}
  - ls -la
  - ls -la ..
  - QUIQQER_OTHER_AUTOLOADERS=KEEP ./tools/phpstan --no-progress --memory-limit=-1
    --debug